<?php

namespace GrandChita\EntityBundle\Repository;

/**
 * EducationProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationProgramRepository extends \Doctrine\ORM\EntityRepository
{
}
