<?php

namespace GrandChita\EntityBundle\Repository;

/**
 * GrandDocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrandDocumentsRepository extends \Doctrine\ORM\EntityRepository
{
}
